### ISSUE TITLE
Building Entity classes from connection.entities metadata

### ISSUE THREAD

**Issue by kristianmandrup** [jjwtay/graphGenTypeorm#2]
I believe that your library assumes that Entity classes are defined separately as per the usual "TypeORM way". I'd love to have the entity classes generated however in order to act as building blocks for further "decoration" as described [here](https://github.com/typestack/class-validator/issues/288#issuecomment-440623609)

As I understand it, the `connectin.entities` is a map, where each key is the `entityKeyName` ie. the entity/class name.

If so, one could then iterate through each entity key and call a function to generate a class decorated by `@Entity` (or via HOF) and store them in a map. Then iterate the field metadata and decorate each Entity field/method as per the constraint directive options that is part of the field metadata generated from the GraphQL type def schema. 

Then I could achieve exactly what I'm looking for, having the constraints also apply on the Entity models directly, not just the mutation resolvers, possibly using different validation frameworks if needed (via transformation/translation). 

Your thoughts?

**Comment by jjwtay** [comment]
This library doesn't require you to write separate TypeORM entity classes they are auto generated as entity schema objects instead. The example shows generating and using dynamically at runtime but you could just as easily have a separate script to build those files and then reference them directly in your man server script. In the Readme there is this block of code

`
const connection = createConnection({
    type: {YOUR_TYPE},
    host: {YOUR_HOST}",
    port: {YOUR_PORT},
    username: {YOUR_USERNAME},
    password: {YOUR_PASSWORD},
    database: {YOUR_DATABASE},
    entities: getEntitySchemas(jsSchema).map(schema => new EntitySchema(schema)),
    synchronize: true
}).then(connection => {
`

getEntitySchemas here takes the js object schema and builds an array of Entity schema objects. The mapping I do is just TypeORM's way to initiate the model from a schema as opposed to the classes directly. In other words the connection.entities[key] is already a key/value mapping of Entity Name to Entity instance.

I am still a little confused by what you are trying to achieve because unless you have found something I am unaware of (entirely possible the typeorm docs last i checked tended to get a bit behind) there is no TypeORM built in validation at all. So any validation done on TypeORM (outside of the context of graphql) is just user defined opt in external behavior provided by an unrelated library called "class-validation". That said to answer your actual question it would be pretty easy to follow the template metaphor instead and build out the entity classes as opposed to entity schemas. I think i mentioned yesterday that originally I had started down that path but felt that entity schemas were cleaner but switching back over should be fairly easy if you truly need it.

Alternatively is your intention is to support multiple API endpoints(like rest and graphql) and you want the automatic support for TypeORM insertions to come from non graphql endpoints like maybe rest or just internal mechanisms to your project? If so you as an alternative solution you could probably get that behavior either functionally wrapping the db mechanisms of typeorm and enforcing their use or alternatively you could probably extend EntitySchema and do the same idea enforcing built in typeorm validation in your projects. These would require you probably to work iwth the library validators.js which is the library that class-validation is built on top of since you'd be working with plain old objects not instances. Sorry just trying to understand what it is you're shooting for so throwing out ideas.

**Comment by kristianmandrup** [comment]
`getEntitySchemas` here takes the js object schema and builds an array of Entity schema objects.

Yup, this is what I figured out, but wasn't sure if this ended up as the metadata itself or was somehow transformed into Entity classes.

In other words the `connection.entities[key]` is already a key/value mapping of Entity Name to Entity instance.

Great! Exactly what I was looking for. That was not clear at all. This is exactly the map I wanted. But I assume you mean classes and not instances? the instances become individual rows in a table/collection of a DB.

"there is no TypeORM built in validation at all. So any validation done on TypeORM (outside of the context of graphql) is just user defined opt in external behavior provided by an unrelated library called `class-validation`."

Yes, I'm perfectly aware of that, but I want to cover all the bases and ideally add the same validation logic in every application layer. That way the DB is not beholden to only a specific API access, such as _GraphQL_, as you point out.

"it would be pretty easy to follow the template metaphor instead and build out the entity classes as opposed to entity schemas."

Yes, I would like to add a template for that as well. Like to keep all the options open.

"Alternatively is your intention is to support multiple API endpoints(like rest and graphql) and you want the automatic support for TypeORM insertions to come from non graphql endpoints like maybe rest or just internal mechanisms to your project?"

Yes, exactly what I want.

"you could probably get that behavior either functionally wrapping the db mechanisms of typeorm and enforcing their use or alternatively you could probably extend EntitySchema and do the same idea enforcing built in typeorm validation in your projects."

I want to do it in a non-intrusive way. That's why I need to build the Entity classes from the typeorm metadata or access them directly if mapping already available as hint they are.

These would require you probably to work iwth the library `validators.js` which is the library that `class-validator` is built on top of since you'd be working with plain old objects not instances. 

Yup, figured that out as well. I have already extended the [graphql-constraint-directive](https://github.com/kristianmandrup/graphql-constraint-directive) for this purpose and made it more directly accessible. 

This is so I can use either these validators as described [here](https://github.com/kristianmandrup/graphql-constraint-directive#reusing-validators) using the same directive or alternatively via [class-validator](https://github.com/typestack/class-validator) with a slight mapping/transformation.

I'm trying to set up an infrastructure to automatically build and sync most of the core application infrastructure from one source of truth, the GraphQL schema.

All in all a similar approach to [TypeGraphQL](https://19majkel94.github.io/type-graphql/) just using a "GraphQL type definitions first" approach, using directives instead of decorators.

I also recently did a lot of work on [graphql-faker](https://github.com/APIs-guru/graphql-faker) to generate a completely mocked or fake GraphQL API backend from a GraphQL type def.

I very much appreciate that you have took the time for this dialogue over these issues. Perhaps we should continue communicating over a different channel if you are interested. What are your goals?
You seem to be going in a similar direction if I'm not mistaken?

**Comment by kristianmandrup** [comment]
I've now extracted the logic I wanted in [graphql-typeorm-validation](https://github.com/kristianmandrup/graphql-typeorm-validation) and removed it from my fork
